title: HBB-Doku
description: docu to hbb
theme: just-the-docs

url: https://masc04.github.io/hbb-doku

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  
plugins:
  - jekyll-default-layout

